Import the packages I will need to work with data. I then read in my data and view the first 5 rows.

In [1]:
import pandas as pd
import numpy as np

In [2]:
from pandas import ExcelWriter
from pandas import ExcelFile

In [3]:
df = pd.read_excel("/Users/brycebangerter/Documents/GDPbyInd_GO_1947-2017.xlsx")

In [4]:
df.head()

,Line,Unnamed: 1,1997,1998,1999,2000,2001,2002,2003,2004,...,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60
0,1.0,All Industries,19990360.0,21045443.0,22152306.0,23115665.0,23168431.0,23345963.0,23859820.0,24743289.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,Private industries,17479694.0,18467857.0,19499301.0,20402832.0,20374764.0,20463468.0,20932267.0,21768949.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,"Agriculture, forestry, fishing, and hunting",305585.0,311863.0,323177.0,318565.0,316476.0,317053.0,326155.0,337353.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,Farms,265001.0,266585.0,272705.0,276157.0,272205.0,271079.0,279015.0,287107.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,"Forestry, fishing, and related activities",40961.0,45122.0,49679.0,43031.0,44572.0,46084.0,47273.0,50341.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

I look at my column names to see if there are any issues with it. There are, so I rename the first unnamed column to be 'Industry' since the column lists various industries. The rest of the unnamed columns don't have any data for them, so it must have been an error when reading in the data, so I dropped those columns.

In [5]:
list(df.columns.values)

['Line',
 'Unnamed: 1',
 '1997',
 '1998',
 '1999',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 2015,
 2016,
 2017,
 'Unnamed: 23',
 'Unnamed: 24',
 'Unnamed: 25',
 'Unnamed: 26',
 'Unnamed: 27',
 'Unnamed: 28',
 'Unnamed: 29',
 'Unnamed: 30',
 'Unnamed: 31',
 'Unnamed: 32',
 'Unnamed: 33',
 'Unnamed: 34',
 'Unnamed: 35',
 'Unnamed: 36',
 'Unnamed: 37',
 'Unnamed: 38',
 'Unnamed: 39',
 'Unnamed: 40',
 'Unnamed: 41',
 'Unnamed: 42',
 'Unnamed: 43',
 'Unnamed: 44',
 'Unnamed: 45',
 'Unnamed: 46',
 'Unnamed: 47',
 'Unnamed: 48',
 'Unnamed: 49',
 'Unnamed: 50',
 'Unnamed: 51',
 'Unnamed: 52',
 'Unnamed: 53',
 'Unnamed: 54',
 'Unnamed: 55',
 'Unnamed: 56',
 'Unnamed: 57',
 'Unnamed: 58',
 'Unnamed: 59',
 'Unnamed: 60']

In [6]:
df.rename(columns={'Unnamed: 1':'Industry'}, inplace=True )

In [7]:
cols = [0, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]

In [8]:
df.drop(df.columns[cols],axis=1,inplace=True)

In [9]:
df.drop([3, 4, 6, 7, 8, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 35, 36, 37, 38, 40, 41, 42, 43, 44, 45, 46, 47, 49, 50, 51, 52, 55, 56, 57, 58, 60, 61, 62, 63, 66, 67, 68, 71, 72, 76, 77, 78, 79, 80, 83, 84, 86, 87, 91, 92, 93, 94, 96, 97, 98, 99, 100, 101, 102, 103], inplace=True)

In [10]:
df

,Industry,1997,1998,1999,2000,2001,2002,2003,2004,2005,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,All Industries,19990360.0,21045443.0,22152306.0,23115665.0,23168431.0,23345963.0,23859820.0,24743289.0,25708373.0,...,26232339.0,24657235.0,25395226.0,25849166.0,26488528.0,26944194.0,27791909.0,28423874.0,28922937.0,29685832
1,Private industries,17479694.0,18467857.0,19499301.0,20402832.0,20374764.0,20463468.0,20932267.0,21768949.0,22703976.0,...,23093071.0,21425920.0,22157829.0,22677194.0,23338398.0,23857548.0,24711585.0,25297369.0,25759312.0,26509648
2,"Agriculture, forestry, fishing, and hunting",305585.0,311863.0,323177.0,318565.0,316476.0,317053.0,326155.0,337353.0,340773.0,...,332054.0,341925.0,346206.0,334751.0,330187.0,349116.0,360553.0,363278.0,386406.0,368920
5,Mining,363111.0,359071.0,345209.0,363788.0,383044.0,352273.0,356473.0,362521.0,373637.0,...,402665.0,380404.0,391196.0,421510.0,457093.0,483581.0,538930.0,511910.0,430511.0,489314
9,Utilities,387458.0,400805.0,481603.0,533090.0,581704.0,453265.0,428734.0,416383.0,442409.0,...,458485.0,389256.0,413795.0,385387.0,367905.0,378470.0,388707.0,388859.0,387458.0,387010
10,Construction,1169941.0,1236213.0,1288506.0,1344638.0,1355661.0,1337016.0,1380227.0,1435585.0,1472057.0,...,1256788.0,1090356.0,1007969.0,978235.0,1012112.0,1048988.0,1103724.0,1181466.0,1232778.0,1220523
11,Manufacturing,4571315.0,4790535.0,4984102.0,5092125.0,4878760.0,4853642.0,4851765.0,4988705.0,5183478.0,...,5101109.0,4469325.0,4717507.0,4870581.0,5037332.0,5126852.0,5211993.0,5245155.0,5315592.0,5432286
33,Wholesale trade,889430.0,929902.0,993361.0,1049623.0,1044599.0,1084394.0,1125258.0,1205928.0,1281181.0,...,1375130.0,1092049.0,1225017.0,1297027.0,1345273.0,1389807.0,1429689.0,1426642.0,1423693.0,1511319
34,Retail trade,1000544.0,1047403.0,1108420.0,1136330.0,1129790.0,1187628.0,1259207.0,1322204.0,1341703.0,...,1285773.0,1222531.0,1314160.0,1327852.0,1378171.0,1422757.0,1462844.0,1520560.0,1575635.0,1630416
39,Transportation and warehousing,714542.0,742990.0,761515.0,762513.0,724682.0,718935.0,739030.0,792640.0,824067.0,...,868488.0,773481.0,812155.0,841826.0,862114.0,875356.0,916706.0,937010.0,932485.0,944343
48,Information,742022.0,817638.0,916965.0,1007829.0,1030395.0,1046523.0,1045667.0,1080359.0,1127540.0,...,1243236.0,1205422.0,1257086.0,1307449.0,1358884.0,1400604.0,1468795.0,1538902.0,1603440.0,1674584
53,"Finance, insurance, real estate, rental, and...",2960929.0,3171176.0,3425675.0,3709571.0,3780037.0,3838567.0,3985333.0,4213838.0,4509140.0,...,4535841.0,4420682.0,4468116.0,4498486.0,4561083.0,4661034.0,4831938.0,4937681.0,5000057.0,5154559
54,Finance and insurance,1131039.0,1252737.0,1415416.0,1588405.0,1606559.0,1606782.0,1654957.0,1724160.0,1821233.0,...,1885133.0,1854314.0,1834213.0,1818414.0,1810126.0,1836531.0,1875935.0,1930916.0,1921125.0,2009038
59,Real estate and rental and leasing,1852199.0,1932963.0,2014265.0,2117382.0,2170865.0,2231072.0,2330544.0,2491764.0,2691915.0,...,2651315.0,2566368.0,2634505.0,2681649.0,2754098.0,2828548.0,2962538.0,3012095.0,3088136.0,3151782
64,Professional and business services,1858010.0,2027416.0,2142897.0,2248019.0,2252926.0,2235064.0,2302904.0,2390424.0,2513746.0,...,2754081.0,2596255.0,2700988.0,2818339.0,2932314.0,2975957.0,3139366.0,3236543.0,3327231.0,3429523
65,"Professional, scientific, and technical se...",1082475.0,1178140.0,1249878.0,1322096.0,1340169.0,1336143.0,1362038.0,1411675.0,1468792.0,...,1624874.0,1548738.0,1588850.0,1639959.0,1687706.0,1694164.0,1766351.0,1807222.0,1862636.0,1889786
69,Management of companies and enterprises,323770.0,346976.0,358704.0,363937.0,367563.0,366707.0,383984.0,393349.0,416825.0,...,445634.0,415297.0,442196.0,474257.0,516011.0,537286.0,578534.0,604295.0,609041.0,625836
70,Administrative and waste management services,454484.0,503860.0,534618.0,560596.0,544828.0,532468.0,557782.0,585581.0,628363.0,...,683569.0,632220.0,670020.0,704344.0,729032.0,745293.0,795832.0,826849.0,856860.0,915113
73,"Educational services, health care, and socia...",1321147.0,1366536.0,1401042.0,1448782.0,1521350.0,1601660.0,1661152.0,1708990.0,1763347.0,...,1926060.0,1975163.0,2017451.0,2065961.0,2113721.0,2138272.0,2187868.0,2288246.0,2357337.0,2439998
74,Educational services,174813.0,181804.0,188622.0,196168.0,207434.0,213993.0,217448.0,216780.0,219583.0,...,249319.0,259043.0,273179.0,278541.0,276909.0,276917.0,279425.0,284453.0,287716.0,294384
75,Health care and social assistance,1146591.0,1185067.0,1212919.0,1253197.0,1314582.0,1388152.0,1443978.0,1492235.0,1543667.0,...,1676752.0,1716120.0,1744264.0,1787425.0,1836969.0,1861613.0,1908875.0,2004651.0,2070808.0,2147055
81,"Arts, entertainment, recreation, accommodati...",782778.0,805968.0,828866.0,868683.0,863326.0,886272.0,913612.0,945290.0,963642.0,...,988945.0,943083.0,955456.0,991284.0,1022509.0,1043974.0,1085357.0,1133982.0,1164377.0,1189124
82,"Arts, entertainment, and recreation",181012.0,185626.0,189791.0,192263.0,194504.0,201848.0,211827.0,218911.0,222636.0,...,249551.0,243097.0,243707.0,251532.0,259110.0,265552.0,274656.0,283770.0,290452.0,307484
85,Accommodation and food services,602318.0,620902.0,639662.0,677139.0,669461.0,685028.0,702297.0,726915.0,741573.0,...,739424.0,699987.0,711740.0,739732.0,763385.0,778428.0,810669.0,850092.0,873780.0,881753
88,"Other services, except government",511501.0,544081.0,554517.0,565236.0,566867.0,570480.0,569896.0,575419.0,566020.0,...,565368.0,525987.0,528186.0,530705.0,547684.0,546942.0,570864.0,575929.0,593003.0,618492
89,Government,2526986.0,2582952.0,2649227.0,2701606.0,2790920.0,2885888.0,2929737.0,2973198.0,2998952.0,...,3135249.0,3231316.0,3237488.0,3172344.0,3150016.0,3086327.0,3080478.0,3126815.0,3164525.0,3179001
90,Federal,781043.0,773781.0,781870.0,789486.0,811024.0,851953.0,897436.0,931177.0,944455.0,...,1022971.0,1074233.0,1113303.0,1087210.0,1077381.0,1016192.0,995492.0,993032.0,993042.0,982569
95,State and local,1746374.0,1811108.0,1869932.0,1915080.0,1983071.0,2036761.0,2033568.0,2042348.0,2054665.0,...,2112237.0,2157083.0,2124231.0,2085166.0,2072655.0,2069419.0,2083785.0,2132039.0,2169378.0,2193775

I want to look at the summary statistics for my data

In [11]:
df.describe()

,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
count,2.800000e+01,2.800000e+01,2.800000e+01,2.800000e+01,2.800000e+01,2.800000e+01,2.800000e+01,2.800000e+01,2.800000e+01,2.800000e+01,2.800000e+01,2.800000e+01,2.800000e+01,2.800000e+01,2.800000e+01,2.800000e+01,2.800000e+01,2.800000e+01,2.800000e+01,2.800000e+01
mean,2.394695e+06,2.522172e+06,2.654013e+06,2.773023e+06,2.784778e+06,2.808178e+06,2.873682e+06,2.981999e+06,3.102420e+06,3.167983e+06,3.225791e+06,3.174838e+06,2.996675e+06,3.083073e+06,3.139869e+06,3.217382e+06,3.272847e+06,3.379050e+06,3.459416e+06,3.521420e+06
std,4.725420e+06,4.982774e+06,5.251860e+06,5.485427e+06,5.483481e+06,5.517016e+06,5.638369e+06,5.854765e+06,6.095555e+06,6.220095e+06,6.331505e+06,6.203345e+06,5.792966e+06,5.977834e+06,6.099384e+06,6.262274e+06,6.384318e+06,6.595847e+06,6.746372e+06,6.866829e+06
min,1.748130e+05,1.818040e+05,1.886220e+05,1.922630e+05,1.945040e+05,2.018480e+05,2.118270e+05,2.167800e+05,2.195830e+05,2.290640e+05,2.401250e+05,2.493190e+05,2.430970e+05,2.437070e+05,2.515320e+05,2.591100e+05,2.655520e+05,2.746560e+05,2.837700e+05,2.877160e+05
25%,4.972468e+05,5.340258e+05,5.495422e+05,5.640760e+05,5.779948e+05,5.609770e+05,5.668675e+05,5.830405e+05,6.127772e+05,6.348765e+05,6.523085e+05,6.540188e+05,6.056618e+05,6.345615e+05,6.609342e+05,6.836950e+05,6.957052e+05,7.415075e+05,7.712105e+05,7.949052e+05
50%,9.449870e+05,9.886525e+05,1.050890e+06,1.092976e+06,1.087194e+06,1.136011e+06,1.192232e+06,1.264066e+06,1.311442e+06,1.345981e+06,1.358122e+06,1.271280e+06,1.148736e+06,1.241052e+06,1.302238e+06,1.352078e+06,1.395206e+06,1.446266e+06,1.473601e+06,1.499664e+06
75%,1.772830e+06,1.841572e+06,1.906015e+06,1.965656e+06,2.030020e+06,2.085339e+06,2.100902e+06,2.129367e+06,2.169435e+06,2.209280e+06,2.260853e+06,2.247006e+06,2.259404e+06,2.251800e+06,2.234287e+06,2.273815e+06,2.310841e+06,2.381536e+06,2.469208e+06,2.540037e+06
max,1.999036e+07,2.104544e+07,2.215231e+07,2.311566e+07,2.316843e+07,2.334596e+07,2.385982e+07,2.474329e+07,2.570837e+07,2.622864e+07,2.668973e+07,2.623234e+07,2.465724e+07,2.539523e+07,2.584917e+07,2.648853e+07,2.694419e+07,2.779191e+07,2.842387e+07,2.892294e+07